mysql:
  dsn: root:wxc11020@tcp(101.33.207.188:3309)/GinChat?charset=utf8mb4&parseTime=True&loc=Local

redis:
  addr: "101.33.207.188:6379"
  password: "wxc11020"
  DB: 0
  poolSize: 30
  minIdleConns: 30